version: '3.8'
services:
  app:
    build: ./
    container_name: app
    restart: ${RESTART_POLICY}
    networks:
      - back-tier
    environment:
      - TZ
      - SERVER_PORT
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}

networks:
  back-tier:
    driver: bridge
    name: back-tier